[package]
name = "hurricane"
version = "0.1.0"
edition = "2021"
authors = ["Dustin Kenefake"]
license = "BSD-3-Clause"
description = "A Heuristics toolbox for QUBO in Rust"
repository = "https://github.com/DKenefake/hurricane/"
readme = "README.md"
homepage = "https://github.com/DKenefake/hurricane/"
keywords = ["QUBO"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
#doctest = false

[dependencies]
sprs = "0.11.1"
ndarray = "0.15.6"
smolprng = "0.1.5"
rayon = "1.8.0"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
target-cpu = "native"

[profile.dev]
lto = false
opt-level = 1
codegen-units = 32
target-cpu = "native"


[profile.bench]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = "unwind"
incremental = false
codegen-units = 1
rpath = false